###
POST http://localhost:3000/signUp HTTP/1.1
content-type: application/json

{
    "firstname": "admin",
    "lastname":"admin", 
    "username": "admin_admin",
    "password": "admin1234567",
    "role":"Admin"
}

###
POST http://localhost:3000/login HTTP/1.1
content-type: application/json

{
    "username": "admin",
    "password": "admin12345"
}