###
POST http://localhost:3000/signUp HTTP/1.1
content-type: application/json

{
    "firstname": "rep",
    "lastname":"repr", 
    "username": "rep",
    "password": "rep12345",
    "role":"Representative"
}

###
POST http://localhost:3000/login HTTP/1.1
content-type: application/json

{
    "username": "rep",
    "password": "rep12345"
}